---
title: NBA Awards Voting - Outlier Ballots Using PCA
author: Robert Huang
date: '2018-12-10'
slug: nba-awards-voting-outlier-ballots-using-pca
categories: []
tags:
  - nba
---



<div id="background" class="section level2">
<h2>Background</h2>
<p>We follow up the previous <a href="https://robhuang.netlify.com/post/2018/11/13/nba-awards-voting-hometown-bias/">post</a> on NBA awards voting with a closer look at the Most Valuable Player (MVP) award. MVP is voted on by a panel of about 100 to 130 media members (a different group depending on the year) after the end of the regular NBA season. Voters rank 5 players on their ballots in preferential order with 1st place receiving 10 points, 2nd place 7 points, 3rd place 5 points, 4th place 3 points, and 5th place 1 point.</p>
<p>There is generally some consensus in the results for each year, with one or two frontrunners finishing far ahead of the other players, a larger group jostling for position in the middle of the pack, and finally a few players receiving some stray votes at the bottom. Despite this groupthink, there are always media members with ballots that deviate more than average from the overall results. These outlier ballots may be the result of votes for players that no other voters mention, placing a player higher than most other voters, or something else. We will attempt to identify extreme ballots and visualize voting results from different seasons of MVP voting using principal component analysis (PCA).</p>
</div>
<div id="dataset" class="section level2">
<h2>Dataset</h2>
<p>Our dataset consists of all MVP votes for five seasons, 2013/14 to 2017/18.</p>
<pre class="r"><code>library(tidyverse)

ballots &lt;- read.csv(&quot;data//nba awards outlier ballots//mvp ballots.csv&quot;, 
                    na = &quot;&quot;, stringsAsFactors = FALSE)

head(ballots, 10)</code></pre>
<pre><code>##               Voter       Affiliation variable         value team  year
## 1        Aaron Falk Salt Lake Tribune       P1  Kevin Durant  OKC 13/14
## 2        Aaron Falk Salt Lake Tribune       P2  LeBron James  MIA 13/14
## 3        Aaron Falk Salt Lake Tribune       P3   Joakim Noah  CHI 13/14
## 4        Aaron Falk Salt Lake Tribune       P4 Blake Griffin  LAC 13/14
## 5        Aaron Falk Salt Lake Tribune       P5  Al Jefferson  CHO 13/14
## 6  Adrian Chavarria       KEYH 850 AM       P1  Kevin Durant  OKC 13/14
## 7  Adrian Chavarria       KEYH 850 AM       P2  LeBron James  MIA 13/14
## 8  Adrian Chavarria       KEYH 850 AM       P3 Stephen Curry  GSW 13/14
## 9  Adrian Chavarria       KEYH 850 AM       P4    Kevin Love  MIN 13/14
## 10 Adrian Chavarria       KEYH 850 AM       P5  James Harden  HOU 13/14</code></pre>
<p>Player placements on ballots are given in the “variable” column. While the NBA uses a scoring system of 10-7-5-3-1 points mentioned above, we will instead use 5-4-3-2-1 points for 1st to 5th place for simpler calculations. This allows us to focus more on player placements on ballots rather than the arbitrary points set by the NBA.</p>
<pre class="r"><code># the created ballots column contains the number of MVP voters for that year
# this will be useful later when summarizing the results
ballots &lt;- ballots %&gt;%
  mutate(place = as.integer(str_extract(variable, &quot;\\d&quot;))) %&gt;%
  group_by(year) %&gt;%
  mutate(pts = max(place) - place + 1,
         ballots = n_distinct(Voter)) %&gt;%
  ungroup() %&gt;%
  select(-variable)</code></pre>
<p>Because we have multiple years of data and want to repeat this analysis for each season of MVP voting, nesting the ballots by year will allow for more convenient handling and access of results.</p>
<pre class="r"><code>mvp &lt;- ballots %&gt;%
  select(year, Voter, value, place, pts, ballots) %&gt;%
  group_by(year) %&gt;%
  nest()</code></pre>
<p>We will start off by summarizing the votes and overall results for MVP for each season. This provides a general picture of how media members filled out their ballots and also a baseline to compare each individual ballot for the identificaiton of outliers. For each player, we obtain the number of votes at each place, total number of mentions, total points, percent of voters that mentioned the player, and the average number of points per voter.</p>
<pre class="r"><code># results1 counts the number of votes at each place (from 1st to 5th)
# results2 totals the number of mentions and points
mvp &lt;- mvp %&gt;%
  mutate(results1 = map(data, . %&gt;%
                          count(value, place) %&gt;%
                          spread(key = place, value = n, fill = 0)),
         results2 = map(data, . %&gt;%
                          group_by(value) %&gt;%
                          summarise(ballots = min(ballots),
                                    mentions = sum(pts &gt; 0),
                                    tot.pts = sum(pts)) %&gt;%
                          ungroup()))

mvp &lt;- mvp %&gt;%
  mutate(results = map2(results1, results2,
                        ~left_join(.x, .y, by = &quot;value&quot;) %&gt;%
                          mutate(pct = mentions / ballots,
                                 avg = tot.pts / ballots) %&gt;%
                          arrange(desc(tot.pts)))) %&gt;%
  select(-(results1:results2))</code></pre>
<p>For 2013/14, we have:</p>
<pre class="r"><code>mvp$results[[1]]</code></pre>
<pre><code>## # A tibble: 17 × 11
##    value        `1`   `2`   `3`   `4`   `5` ballots mentions tot.pts   pct   avg
##    &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;int&gt;    &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 Kevin Dur…   119     6     0     0     0     125      125     619 1     4.95 
##  2 LeBron Ja…     6   118     1     0     0     125      125     505 1     4.04 
##  3 Blake Gri…     0     1    66    30     7     125      104     269 0.832 2.15 
##  4 Joakim No…     0     0    32    50    12     125       94     208 0.752 1.66 
##  5 James Har…     0     0     7    10    20     125       37      61 0.296 0.488
##  6 Stephen C…     0     0     4     9    19     125       32      49 0.256 0.392
##  7 Chris Paul     0     0     5     6     2     125       13      29 0.104 0.232
##  8 Paul Geor…     0     0     1     4    16     125       21      27 0.168 0.216
##  9 Al Jeffer…     0     0     2     4    12     125       18      26 0.144 0.208
## 10 LaMarcus …     0     0     2     2    10     125       14      20 0.112 0.16 
## 11 Kevin Love     0     0     2     3     6     125       11      18 0.088 0.144
## 12 Tim Duncan     0     0     1     3     7     125       11      16 0.088 0.128
## 13 Tony Park…     0     0     2     2     5     125        9      15 0.072 0.12 
## 14 Dirk Nowi…     0     0     0     1     4     125        5       6 0.04  0.048
## 15 Carmelo A…     0     0     0     1     1     125        2       3 0.016 0.024
## 16 Goran Dra…     0     0     0     0     3     125        3       3 0.024 0.024
## 17 Mike Conl…     0     0     0     0     1     125        1       1 0.008 0.008</code></pre>
<p>Kevin Durant won the MVP, with LeBron James stealing a few first place votes to prevent Durant from winning the award unanimously. Blake Griffin and Joakim Noah battled for third place. Thirteen other players received mentions, resulting in a larger pool of candidates than any of the next four years. A quick reminder that the points used here differ from the actual values used by the NBA, but the standings are very close to the official results.</p>
</div>
<div id="point-differentials" class="section level2">
<h2>Point Differentials</h2>
<p>A simple way of determining outlier ballots is to compare the number of points a voter gives to each player compared to the same players’ average points from all voters. Summing these absolute differences gives an overall point differential for each voter. As an example, let us look at ex-Salt Lake Tribune writer Aaron Falk’s 2013/14 ballot:</p>
<pre class="r"><code>mvp$data[[1]] %&gt;%
  filter(Voter == &quot;Aaron Falk&quot;)</code></pre>
<pre><code>## # A tibble: 5 × 5
##   Voter      value         place   pts ballots
##   &lt;chr&gt;      &lt;chr&gt;         &lt;int&gt; &lt;dbl&gt;   &lt;int&gt;
## 1 Aaron Falk Kevin Durant      1     5     125
## 2 Aaron Falk LeBron James      2     4     125
## 3 Aaron Falk Joakim Noah       3     3     125
## 4 Aaron Falk Blake Griffin     4     2     125
## 5 Aaron Falk Al Jefferson      5     1     125</code></pre>
<p>Compare the above table with the overall results:</p>
<pre class="r"><code>(a.falk.14 &lt;- mvp$data[[1]] %&gt;%
   filter(Voter == &quot;Aaron Falk&quot;) %&gt;%
   select(value, Voter, pts) %&gt;%
   complete(value = mvp$results[[1]]$value,
            fill = list(pts = 0)) %&gt;%
   left_join(mvp$results[[1]] %&gt;%
               select(value, avg),
             by = &quot;value&quot;) %&gt;%
   arrange(desc(pts)) %&gt;%
   mutate(diff = pts - avg))</code></pre>
<pre><code>## # A tibble: 17 × 5
##    value             Voter        pts   avg    diff
##    &lt;chr&gt;             &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
##  1 Kevin Durant      Aaron Falk     5 4.95   0.0480
##  2 LeBron James      Aaron Falk     4 4.04  -0.0400
##  3 Joakim Noah       Aaron Falk     3 1.66   1.34  
##  4 Blake Griffin     Aaron Falk     2 2.15  -0.152 
##  5 Al Jefferson      Aaron Falk     1 0.208  0.792 
##  6 Carmelo Anthony   &lt;NA&gt;           0 0.024 -0.024 
##  7 Chris Paul        &lt;NA&gt;           0 0.232 -0.232 
##  8 Dirk Nowitzki     &lt;NA&gt;           0 0.048 -0.048 
##  9 Goran Dragic      &lt;NA&gt;           0 0.024 -0.024 
## 10 James Harden      &lt;NA&gt;           0 0.488 -0.488 
## 11 Kevin Love        &lt;NA&gt;           0 0.144 -0.144 
## 12 LaMarcus Aldridge &lt;NA&gt;           0 0.16  -0.16  
## 13 Mike Conley       &lt;NA&gt;           0 0.008 -0.008 
## 14 Paul George       &lt;NA&gt;           0 0.216 -0.216 
## 15 Stephen Curry     &lt;NA&gt;           0 0.392 -0.392 
## 16 Tim Duncan        &lt;NA&gt;           0 0.128 -0.128 
## 17 Tony Parker       &lt;NA&gt;           0 0.12  -0.12</code></pre>
<p>Falk gave Kevin Durant a difference of 0.048 points compared to average, LeBron James -0.04 points compared to average, and so on. Note that we also include all the players that showed up on other voters’ ballots, but that Falk did not vote for. Summing these absolute differences gives 4.352, Falk’s overall difference in points for his ballot.</p>
<p>This score is calculated for every voter across all five years:</p>
<pre class="r"><code>mvp &lt;- mvp %&gt;%
  mutate(raw.diff = map2(data, results,
                           ~.x %&gt;%
                             select(Voter, value, pts) %&gt;%
                             complete(Voter, nesting(value = .y$value), 
                                      fill = list(pts = 0)) %&gt;%
                             left_join(.y %&gt;%
                                         select(value, avg),
                                       by = &quot;value&quot;) %&gt;%
                             group_by(Voter) %&gt;%
                             summarise(diff = sum(abs(avg - pts))) %&gt;%
                             arrange(desc(diff))
                         )
         )</code></pre>
<p>The 2013/14 voters with the greatest deviations from average are:</p>
<pre class="r"><code>mvp$raw.diff[[1]]</code></pre>
<pre><code>## # A tibble: 125 × 2
##    Voter              diff
##    &lt;chr&gt;             &lt;dbl&gt;
##  1 Al McCoy           13.1
##  2 Cedric Maxwell     11.4
##  3 Ron Tillery        11.4
##  4 Ted Davis          10.9
##  5 Dominique Wilkins  10.9
##  6 Eric Hasseltine    10.5
##  7 Brendan Brown      10.4
##  8 Bob Cooney         10.4
##  9 Steve Martin       10.3
## 10 Dave Johnson       10.3
## # ℹ 115 more rows</code></pre>
<p>These scores pick out voters that deviate the most compared to other voters in terms of the raw placements of players on their ballots, but this ignore the variances and correlations among the all the ballots. As an example of how variance comes into play, suppose there are 100 voters. Player A receives one fifth place vote but is ignored by all other media. This results in a point differential of 0.99 for the only voter of Player A. Player B receives 50 first place votes and 49 fith place votes. If another voter gives Player B a fourth place vote, this results in a differential that is the same as the first case despite the uneven situations.</p>
<p>For an example of correlation among ballots, suppose Players C and D are teammates who end up splitting ballots. Because of that, they generally do not appear on any ballots together. If there exists a media member that votes for both players, the scores calculated above would not capture this idiosyncrasy.</p>
</div>
<div id="principal-component-analysis" class="section level2">
<h2>Principal Component Analysis</h2>
<p>Principal component analysis (PCA) is a technique that can be used to simplify high dimensional data into a fewer number of new variables (principal components) that still contain information about the entire dataset. We will use it here to visualize MVP ballots and identify outlier voters.</p>
<p>As a preliminary step, we need to transform our data into a form that is suitable for PCA. The data will be set up such that:</p>
<ul>
<li><p>Each variable (column) is a player that received at least one mention
from any voter for that season.</p></li>
<li><p>Each observation (row) is a voter.</p></li>
<li><p>Each value is the number of points a player has received from a
voter, or equivalently, the number of points a voter has given to a player (5 for 1st
place, 4 for 2nd place, … and 0 if not mentioned).</p></li>
</ul>
<p>For 2013/14, this results in:</p>
<pre class="r"><code>mvp &lt;- mvp %&gt;%
  mutate(votes = map(data, . %&gt;%
                       select(-place, -ballots) %&gt;%
                       spread(key = value, value = pts, fill = 0) %&gt;%
                       as.data.frame() %&gt;%
                       column_to_rownames(var = &quot;Voter&quot;)))

mvp$votes[[1]][1:10, 1:4]</code></pre>
<pre><code>##                  Al Jefferson Blake Griffin Carmelo Anthony Chris Paul
## Aaron Falk                  1             2               0          0
## Adrian Chavarria            0             0               0          0
## Al Iannazzone               0             3               0          0
## Al McCoy                    0             0               0          1
## Alan Horton                 0             3               0          0
## Andy Vasquez                1             2               0          0
## Anthony Slater              0             3               0          0
## Bill Land                   0             3               0          0
## Bill Oram                   0             3               0          0
## Bill Reiter                 0             3               0          0</code></pre>
<p>We can apply PCA to each year’s data. Before doing that, we need to make one adjustment. If there are players that receive unanimous votes at only one ballot slot (Stephen Curry received all the first place votes in 2015/16), the columns for those players will be constant and provide no extra information. These columns need to be removed.</p>
<pre class="r"><code>mvp &lt;- mvp %&gt;%
  mutate(keep = map(votes,
                    function(x) map_lgl(x, function(y) length(unique(y)) &gt; 1)),
         votes = map2(votes, keep, function(x, y) x[, y])) %&gt;%
  select(-keep)</code></pre>
<p>PCA is applied for all years:</p>
<pre class="r"><code>mvp &lt;- mvp %&gt;%
  mutate(pca = map(votes, ~prcomp(., scale. = TRUE)))</code></pre>
</div>
<div id="section" class="section level2">
<h2>2013/14</h2>
<p>We will start with the results for 2013/14, visualizing the MVP voting using a biplot of the first two principal components.</p>
<pre class="r"><code>library(ggfortify)

autoplot(mvp$pca[[1]],
         loadings = TRUE,
         loadings.label = TRUE,
         label = TRUE, shape = FALSE) +
  theme_bw()</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-13-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The loadings (in red) shed light on the general structures of MVP ballots for the season. Compare the above plot to the voting results shown earlier. Kevin Durant and LeBron James are negatively correlated because media voters chose between the two players for first and second place on their ballots. Los Angeles Clippers Blake Griffin and Chris Paul are negatively correlated because the teammates split votes, with voters rarely placing both players on their ballots. This can be confirmed by looking through the raw data.</p>
<p>To gain insight into how voters are being graphed on the biplot, they can be colored based on groupings we want to study in more detail. First, we look at how media used their first and second place slots.</p>
<pre class="r"><code>groups.14.1 &lt;- mvp$votes[[1]] %&gt;%
  mutate(group.1 = case_when(`Kevin Durant` == 5 &amp; `LeBron James` == 4 ~
                               &quot;1: Durant, 2: LeBron&quot;,
                             `Kevin Durant` == 4 &amp; `LeBron James` == 5 ~
                               &quot;1: LeBron, 2: Durant&quot;,
                             TRUE ~
                               &quot;1: Durant, 2: Griffin&quot;)) %&gt;%
  select(group.1)

autoplot(mvp$pca[[1]],
         loadings = TRUE,
         loadings.label = TRUE,
         label = TRUE, shape = FALSE,
         data = groups.14.1, colour = &quot;group.1&quot;) +
  scale_color_manual(name = &quot;&quot;, values = c(&quot;blue&quot;, &quot;orange&quot;, &quot;black&quot;)) +
  theme_bw()</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-14-1.png" width="864" style="display: block; margin: auto;" /></p>
<p>Most voters have Kevin Durant first and LeBron James second. The five voters that have LeBron first also have Durant second and are plotted in the top right along the LeBron James loading. Chris Sheridan, the only voter to have leave LeBron outside his top two, is plotted farther left than any other observation. Sheridan is an outlier using PCA, something that looking at the raw score differentials alone does not tell us. Under that metric, Sheridan ranks 42 out of 125 for largest score differential.</p>
<p>What separates the two groups of voters that have LeBron first on their ballots? Looking at how they ranked Blake Griffin and Joakim Noah—the third and fourth place finishers, respectively—on their ballots provides the answer.</p>
<pre class="r"><code>groups.14.2 &lt;- mvp$votes[[1]] %&gt;%
  mutate(group.2 = ifelse(`Blake Griffin` &gt; 0 &amp; `Joakim Noah` &gt; 0,
                          &quot;both Griffin &amp; Noah&quot;,
                          ifelse(`Blake Griffin` &gt; 0 | `Joakim Noah` &gt; 0,
                                 &quot;one of Griffin/Noah&quot;, &quot;neither&quot;))) %&gt;%
  select(contains(&quot;group&quot;))

autoplot(mvp$pca[[1]],
         loadings = TRUE,
         loadings.label = TRUE,
         label = TRUE, shape = FALSE,
         data = groups.14.2, colour = &quot;group.2&quot;) +
  scale_color_manual(name = &quot;&quot;, values = c(&quot;black&quot;, &quot;green&quot;, &quot;purple&quot;)) +
  theme_bw()</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-15-1.png" width="864" style="display: block; margin: auto;" /></p>
<p>Observations are grouped by whether they included both Griffin and Noah (black), just one of Griffin and Noah (purple), or left both off (green). Most of the voters that included both are plotted higher with the Griffin/Noah loadings. Al McCoy and Cedric Maxwell are separated from the other three LeBron voters because they did not include both Griffin and Noah on their ballots. Maxwell included only Noah and McCoy voted for neither. Both voters also scored the highest using the point differentials seen above.</p>
<p>The other voter with that had a high score (tied with Maxwell) is Ron Tillery, plotted at the bottom of the biplot. Tillery is an outlier because he placed LeBron first, left off both Griffin and Noah, and was the only media member to mention Mike Conley.</p>
</div>
<div id="section-1" class="section level2">
<h2>2017/18</h2>
<p>We will look at one more year of MVP voting, choosing 2017/18 because the results for the other years are less interesting.</p>
<pre class="r"><code>mvp$results[[5]]</code></pre>
<pre><code>## # A tibble: 13 × 11
##    value     `1`   `2`   `3`   `4`   `5` ballots mentions tot.pts     pct    avg
##    &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;int&gt;    &lt;int&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
##  1 James …    86    15     0     0     0     101      101     490 1       4.85  
##  2 LeBron…    15    79     7     0     0     101      101     412 1       4.08  
##  3 Anthon…     0     7    70    14     4     101       95     270 0.941   2.67  
##  4 Damian…     0     0    12    40    27     101       79     143 0.782   1.42  
##  5 Gianni…     0     0     1    18    16     101       35      55 0.347   0.545 
##  6 Russel…     0     0     6    10    16     101       32      54 0.317   0.535 
##  7 Kevin …     0     0     3    10    21     101       34      50 0.337   0.495 
##  8 DeMar …     0     0     1     7     6     101       14      23 0.139   0.228 
##  9 LaMarc…     0     0     0     1     3     101        4       5 0.0396  0.0495
## 10 Joel E…     0     0     0     0     4     101        4       4 0.0396  0.0396
## 11 Stephe…     0     0     0     1     2     101        3       4 0.0297  0.0396
## 12 Jimmy …     0     0     1     0     0     101        1       3 0.00990 0.0297
## 13 Victor…     0     0     0     0     2     101        2       2 0.0198  0.0198</code></pre>
<p>James Harden won his first MVP award this season, garnering 86 of the 101 first place votes. Like 2013/14, LeBron James stole a few first place votes but finished solidly in second place. Anthony Davis received a majority of the third place votes while the bottom half of the ballot did not show as much consensus.</p>
<pre class="r"><code>autoplot(mvp$pca[[5]],
         loadings = TRUE,
         loadings.label = TRUE,
         label = TRUE, shape = FALSE) +
  theme_bw()</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-17-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>In the PCA plot, the Harden and LeBron loadings have opposite directions because of how they split the first and second place votes (similar to Kevin Durant and LeBron in 2013/14). While only three media members voted for Stephen Curry, none of those that did also voted for Warrior teammate Durant (similar to Blake Griffin/Chris Paul in 2013/14).</p>
<p>To see how PCA is grouping voters, we color the observations by how they used their first and second place votes.</p>
<pre class="r"><code>groups.18 &lt;- mvp$votes[[5]] %&gt;%
  mutate(group.1 = case_when(`James Harden` == 5 &amp; `LeBron James` == 4 ~
                               &quot;1: Harden, 2: LeBron&quot;,
                             `James Harden` == 5 &amp; `Anthony Davis` == 4 ~
                               &quot;1: Harden, 2: Davis&quot;,
                             `LeBron James` == 5 &amp; `James Harden` == 4 ~
                               &quot;1: LeBron, 2: Harden&quot;,
                             TRUE ~
                               &quot;1: LeBron, 2: Davis&quot;)) %&gt;%
  select(group.1)

autoplot(mvp$pca[[5]],
         loadings = TRUE,
         loadings.label = TRUE,
         label = TRUE, shape = FALSE,
         data = groups.18, colour = &quot;group.1&quot;) +
  scale_color_manual(name = &quot;&quot;, values = c(&quot;green3&quot;, &quot;black&quot;, &quot;blue&quot;, &quot;orange&quot;)) +
  theme_bw()</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-18-1.png" width="864" style="display: block; margin: auto;" /></p>
<p>The media members are plotted along the first principal component by how they voted first and second.
The largest group of voters have Harden first and LeBron second and have values close to zero, along the center of the graph. Voters with LeBron first and Harden second have positive values, and those with Harden first and Davis second have negative values.</p>
<p>Joe Cowley and Gary Washburn stand out as obvious outliers.</p>
<pre class="r"><code>mvp$data[[5]] %&gt;%
  filter(Voter == &quot;Joe Cowley&quot;)</code></pre>
<pre><code>## # A tibble: 5 × 5
##   Voter      value                 place   pts ballots
##   &lt;chr&gt;      &lt;chr&gt;                 &lt;int&gt; &lt;dbl&gt;   &lt;int&gt;
## 1 Joe Cowley LeBron James              1     5     101
## 2 Joe Cowley James Harden              2     4     101
## 3 Joe Cowley Jimmy Butler              3     3     101
## 4 Joe Cowley Anthony Davis             4     2     101
## 5 Joe Cowley Giannis Antetokounmpo     5     1     101</code></pre>
<p>The main reason Cowley is outlier is because of his vote for Jimmy Butler. Not only was he the only voter to give Butler a mention, he gave put the Timberwolf third on his ballot.</p>
<pre class="r"><code>mvp$data[[5]] %&gt;%
  filter(Voter == &quot;Gary Washburn&quot;)</code></pre>
<pre><code>## # A tibble: 5 × 5
##   Voter         value             place   pts ballots
##   &lt;chr&gt;         &lt;chr&gt;             &lt;int&gt; &lt;dbl&gt;   &lt;int&gt;
## 1 Gary Washburn LeBron James          1     5     101
## 2 Gary Washburn James Harden          2     4     101
## 3 Gary Washburn Damian Lillard        3     3     101
## 4 Gary Washburn Russell Westbrook     4     2     101
## 5 Gary Washburn Victor Oladipo        5     1     101</code></pre>
<p>Washburn was one of two voters to give Victor Oladipo a vote and one of six voters to leave Anthony Davis off his ballot. This is in addition to picking LeBron over Harden at first.</p>
<pre class="r"><code>mvp$data[[5]] %&gt;%
  filter(Voter == &quot;Bill Simmons&quot;)</code></pre>
<pre><code>## # A tibble: 5 × 5
##   Voter        value          place   pts ballots
##   &lt;chr&gt;        &lt;chr&gt;          &lt;int&gt; &lt;dbl&gt;   &lt;int&gt;
## 1 Bill Simmons James Harden       1     5     101
## 2 Bill Simmons Anthony Davis      2     4     101
## 3 Bill Simmons LeBron James       3     3     101
## 4 Bill Simmons Damian Lillard     4     2     101
## 5 Bill Simmons Victor Oladipo     5     1     101</code></pre>
<pre class="r"><code>mvp$data[[5]] %&gt;%
  filter(Voter == &quot;Diego Martinez Cabrera&quot;)</code></pre>
<pre><code>## # A tibble: 5 × 5
##   Voter                  value             place   pts ballots
##   &lt;chr&gt;                  &lt;chr&gt;             &lt;int&gt; &lt;dbl&gt;   &lt;int&gt;
## 1 Diego Martinez Cabrera LeBron James          1     5     101
## 2 Diego Martinez Cabrera James Harden          2     4     101
## 3 Diego Martinez Cabrera Damian Lillard        3     3     101
## 4 Diego Martinez Cabrera Anthony Davis         4     2     101
## 5 Diego Martinez Cabrera Russell Westbrook     5     1     101</code></pre>
<p>Bill Simmons and Diego Martinez Cabrera also stand out, but not to the extent of Cowley and Washburn. Simmons separated himself from the rest of the media because he was the other voter to give Oladipo a mention. The reason for Cabrera is less apparent, but is because of his combination of player placements.</p>
<p>Compare the plot to the results given by point differentials.</p>
<pre class="r"><code>mvp$raw.diff[[5]]</code></pre>
<pre><code>## # A tibble: 101 × 2
##    Voter              diff
##    &lt;chr&gt;             &lt;dbl&gt;
##  1 NBA Fan Component 10.1 
##  2 Gary Washburn      9.90
##  3 Dennis Scott       9.76
##  4 Joe Cowley         8.69
##  5 Marv Albert        7.92
##  6 Sherrod Blakely    7.50
##  7 Richard Walker     7.41
##  8 Elliott Teaford    7.31
##  9 Chris Webber       7.01
## 10 Ric Bucher         6.48
## # ℹ 91 more rows</code></pre>
<p>Both Cowley and Washburn finish high, but Simmons and Cabrera do not. The point differential metric rates the NBA Fan Component (fan vote) as the ballot that differs the most compared to average, but it is not noticeable as an outlier using the PCA plot.</p>
<p>Similar analysis can be repeated for the other seasons.</p>
</div>
